apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubelet-maxpods-patcher
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kubelet-maxpods-patcher
  template:
    metadata:
      labels:
        name: kubelet-maxpods-patcher
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
      - operator: Exists
      containers:
      - name: patcher
        image: alpine
        securityContext:
          privileged: true
        command: ["/bin/sh", "-c"]
        args:
          - |
            sed -i 's/"maxPods": [0-9]*/"maxPods": 110/g' /host/etc/kubernetes/kubelet/config.json;
            chroot /host systemctl restart kubelet;
            sleep 3600;
        volumeMounts:
        - name: host-root
          mountPath: /host
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
