adminUser: admin
adminPassword: antiatropos

service:
  type: ClusterIP

persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 192Mi
  limits:
    cpu: 400m
    memory: 384Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        editable: true

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: ALL
