apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQk5ZY1JYcVZ2dm93RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBME1qTXhPREEwTURGYUZ3MHpOakEwTWpBeE9EQTVNREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN2cHYwRVRIREIxeVRjVVFxa21Xd2Z2YnE0Z3d1bm9HK0w0MkIvaUV0N3h1NVhTMjZQWVlwNURGckYKUTJoUTRndDlENDUwNXlHNkN0eCtWVXBncExpeUxEU3pMdEM2VHUrUm5uSEY0NHRHZ1NJQm9GaG9TaXhzWFV3SQoxU3E1NVBIeHhPQmo3OGJxRFVxL2R3eE1xOVk1TzBINmkwV1ZaZHMvTmhaMk9rd1dJeUJnYy9Rckhpb2ZJZm1qCkVhZ0psRm9Sb1c2L2RjajBiOThOMi9zaWt1blRhQldJSGpPay9ESkNiWldzU0JtOTBBY0V3dEdnN1Bhc1hOcUsKaWwydWxlMG9PYk9zTyszbDhpeU9nYktROHFDbFgwSU03UVN2Y1J4YnYwK2FCYXpxVS9BRkhMY1VmTW1VMXVKRwpLdGVuTUxzNnBLdlpyRU9EOFlacklkYmkyZDBaQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTVm43TWdjYkhCNE9wNFc0WEhLYlNPeWdBdDREQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQSsxc0Rjc1RJcQp0T3V4Nk5OMkUrTFlYOFEvTk9qWlhSQVhSeDlOdXhoL0RCRmJwTjUrTzg2VWROL3BJamI0WGUyTVRGaytCTXZnCmUyWk9NNGJFQTlLR3JPc1RhK3VBL3pKZFhjUXZ0MG00Kzd5T3VqcklHOGhuOTlZSjRlTmxYYk9nV3NOTmVDMnEKT01DVFFPdGtJNVlMNFNET2ZDRUlsOEpBU0QvZTNRd0p6Mk15bnNIR2F4azZYZ3VnVkgzekVQcVNRL3FZa2pQTgpDY0ZMNXF1WWVUODUzM3g0SENKb1dmblZReHlaOVJ2V1Y0eThpT3JqbTV3Z2xvN2U3NkRmaTBwTnczRS80MysxCisrdXdWYmhZZTE0OUhyK3FzWU1YbGFiTFJmeHhXT2RxdzMxbXdJeitSSHF5V2U4V3prZnhUVGlmQjZNVVJyQXgKRWVKQWkwdWMxSkRMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://D3CBAF956940D075AE61BB6193A93256.gr7.ap-south-1.eks.amazonaws.com
    name: antiatropos
contexts:
  - context:
      cluster: antiatropos
      user: antiatropos-hf-user
    name: antiatropos
current-context: antiatropos
preferences: {}
users:
  - name: antiatropos-hf-user
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: aws
        args:
          - eks
          - get-token
          - --region
          - ap-south-1
          - --cluster-name
          - antiatropos
        env:
          - name: AWS_STS_REGIONAL_ENDPOINTS
            value: regional
          - name: AWS_DEFAULT_REGION
            value: ap-south-1
        interactiveMode: IfAvailable

